"""initial schema

Revision ID: 16c21103cf7b
Revises: 
Create Date: 2026-01-03 12:55:10.116155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c21103cf7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('date_of_leaving', sa.Date(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('aadhar_number', sa.String(length=12), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('uan_number', sa.String(length=20), nullable=True),
    sa.Column('esi_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_table('payroll_periods',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=20), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_payroll_period_year_month')
    )
    op.create_table('monthly_payroll',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('present_days', sa.Integer(), nullable=False),
    sa.Column('paid_days', sa.Integer(), nullable=False),
    sa.Column('absent_days', sa.Integer(), nullable=False),
    sa.Column('late_marks', sa.Integer(), nullable=False),
    sa.Column('privilege_leave', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('sick_leave', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('casual_leave', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conveyance_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cca', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_employee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('esi_employee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loan_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tds', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_employer', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('esi_employer', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ctc_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'payroll_period_id', name='uq_monthly_payroll_employee_period')
    )
    op.create_index(op.f('ix_monthly_payroll_employee_id'), 'monthly_payroll', ['employee_id'], unique=False)
    op.create_index(op.f('ix_monthly_payroll_payroll_period_id'), 'monthly_payroll', ['payroll_period_id'], unique=False)
    op.create_table('salary_structures',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conveyance_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cca', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pf_applicable', sa.Boolean(), nullable=False),
    sa.Column('esi_applicable', sa.Boolean(), nullable=False),
    sa.Column('pt_applicable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_structures_employee_id'), 'salary_structures', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_structures_employee_id'), table_name='salary_structures')
    op.drop_table('salary_structures')
    op.drop_index(op.f('ix_monthly_payroll_payroll_period_id'), table_name='monthly_payroll')
    op.drop_index(op.f('ix_monthly_payroll_employee_id'), table_name='monthly_payroll')
    op.drop_table('monthly_payroll')
    op.drop_table('payroll_periods')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
